#!/bin/bash

resultFile="results.txt"
outputFile="output.txt"
dataFile="data1.cvs"
> $resultFile
> $outputFile
> $dataFile
# number of threads:
for t in 1 2 4
do
	echo _NUMT\(Number of Threads\) = $t
	echo _NUMT\(Number of Threads\) = $t >> $outputFile
	# number of subdivisions
	for s in 10 20 40 80 160 320 640 1280
	do
		echo \|
		echo \| >> $outputFile
		echo .---_NUMS\(Number of subdivisions\) = $s
		echo .---_NUMS\(Number of subdivisions\) = $s >> $outputFile
		g++ -D_NUMT=$t -D_NUMS=$s project_1_thread_prog.cpp -o thread_prog -lm -fopenmp
		./thread_prog >> $outputFile
	done
	echo --------------------------------------------------------- >> $outputFile
done
g++ -o speed_prog project_1_speed_prog.cpp
./speed_prog >> $outputFile
rm thread_prog speed_prog $resultFile
cat $outputFile
