#!/bin/bash

resultFile="results.txt"
outputFile="output.txt"
dataFile="data.csv"
> $resultFile
> $outputFile
> $dataFile
# number of threads:
for t in 1 2 4 8 16 32
do
	for m in 0 1
	do
		for tp in 0 1
		do
			echo _NUMT\(Number of Threads\) = $t
			echo _METHOD = $m
			echo _TYPE = $tp
			g++ -D_NUMT=$t -D_METHOD=$m -D_TYPE=$tp project_2_thread_prog.cpp -o thread_prog -lm -fopenmp
			./thread_prog
			echo ---------------------------------------------------------
		done
	done
done
g++ -o speed_prog project_2_speed_prog.cpp
./speed_prog
rm thread_prog speed_prog $resultFile
cat $dataFile
