#!/bin/bash

# number of threads:
for t in 1 2 4
do
	echo _NUMT\(Number of Threads\) = $t
	g++ -D_NUMT=$t project_2_thread_prog.cpp -o thread_prog -lm -fopenmp
	./thread_prog
	echo ---------------------------------------------------------
done
#g++ -o speed_prog project_2_speed_prog.cpp
#./speed_prog >> $outputFile
#rm thread_prog speed_prog $resultFile
#cat $outputFile
